.\" Manpage for ith.
.\" Contact weldon@b.rontosaur.us to correct errors or typos
.TH ith 1 "14 Dec 2013" "1.0" "User Commands"
.SH NAME
ith \- calculate information theory properties of files
.SH SYNOPSIS
ith [COMMAND] [OPTIONS]
.SH DESCRIPTION
ith builds a Probability Mass Function (PMF) from its input and performs information-theoretic calculations on that PMF.
.SH COMMANDS
.IP -h	
Print usage and exit
.IP -e	
Compute entropy (default if no command specified)
.IP -k
Compute Kullback-Leibler divergence against a uniform distribution
.IP -p	
Print the resulting PMF; semantics will vary based on the alphabet chosen below (in particular, 
.B word
will display the string parsed as a word; the rest will display numbers or memory locations since wide char streams make terminals futzy).
.IP -x	
Run the Pearson chi-squared test against the null hypothesis of uniform distribution over the alphabet
.SH OPTIONS
.IP "-a 1 | 8 | 16 | 32 | 64 | char | word | wchar | wword"
Choose the alphabet the input is read over. A number is that number of bits (so, bits, bytes, shorts, ints, and longs, on many platforms). 
.B char 
and 
.B wchar 
are whatever 
.BR fgetc(3) 
and 
.BR fgetwc(3) 
read on your platform. 
.B word
is a textual word, separated by characters that satisfy 
.BR isspace(3)
or 
.BR ispunct(3)
; 
.B wword 
is the wide character analog. Note that this is a different standard than 
.BR wc(1)
uses to determine word divisions.
.IP "-f filename"
Read from the specified file. Default is stdin.
.IP "-t"
Be terse; simply print the number rather than a sentence. (Has no effect when -p is specified.)
.IP "-u 2 | e | 10"
Choose the unit of information for calculation. 2 is bits (this is the default). e is nats (use 
.BR log(3)
rather than 
.BR log2(3)
). 10 is digits (use 
.BR log10(3)
rather than 
.BR log2(3)
).
.SH AUTHOR
Weldon Goree (weldon@libith.org)

